; PlatformIO Project Configuration File
; ESP32 Firebasket Ignition Firmware

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Serial Monitor Baud Rate
monitor_speed = 115200
upload_speed = 115200

; Build Options
build_flags = 
    -D CORE_DEBUG_LEVEL=0
